-- MySQL Script generated by MySQL Workbench
-- Tue Sep 12 16:43:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Area` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `sigla` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `superArea` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sigla`, `superArea`),
  CONSTRAINT `fk_area_area1`
    FOREIGN KEY (`superArea`)
    REFERENCES `mydb`.`Area` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_area_area1_idx` ON `mydb`.`Area` (`superArea` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `Sigla` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cargaHoraria` INT NOT NULL,
  `custo` FLOAT NOT NULL,
  `area_sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_Curso_area`
    FOREIGN KEY (`area_sigla`)
    REFERENCES `mydb`.`Area` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Curso_area_idx` ON `mydb`.`Curso` (`area_sigla` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `CPF` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`CPF`, `curso`),
  CONSTRAINT `fk_Professor_Curso1`
    FOREIGN KEY (`curso`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Professor_Curso1_idx` ON `mydb`.`Professor` (`curso` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `CPF` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `dataNasc` DATE NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Matricula` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `dataMatricula` DATE NOT NULL,
  `pago` TINYINT NOT NULL,
  `curso` VARCHAR(5) NOT NULL,
  `aluno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`curso`, `aluno`),
  CONSTRAINT `fk_Matricula_Curso1`
    FOREIGN KEY (`curso`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`aluno`)
    REFERENCES `mydb`.`Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Matricula_Curso1_idx` ON `mydb`.`Matricula` (`curso` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Matricula_Aluno1_idx` ON `mydb`.`Matricula` (`aluno` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Modulo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Modulo` (
  `sigla` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`sigla`),
  CONSTRAINT `fk_modulo_Curso1`
    FOREIGN KEY (`curso`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_modulo_Curso1_idx` ON `mydb`.`Modulo` (`curso` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Topico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Topico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Topico` (
  `sigla` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `horas` INT NOT NULL,
  `modulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sigla`, `modulo`),
  CONSTRAINT `fk_topico_modulo1`
    FOREIGN KEY (`modulo`)
    REFERENCES `mydb`.`Modulo` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_topico_modulo1_idx` ON `mydb`.`Topico` (`modulo` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
